Persist result from `tokens` event
bitfocus/companion-module-youtube-live pull request #126
Opened 2024-10-23 20:13 UTC by astellingwerf

2025-06-17 01:27 UTC, jswalden commented
I have been diving extremely deeply into OAuth at the spec/client implementation level -- with aim to maybe add some built-in OAuth support to Companion so everyone doesn't have to manually reimplement authorization and periodic exchange-refresh-for-authetication-token operations.  That's given me well more than enough knowledge basis to be able to look at this.

The Google Sheets module already periodically exchanges refresh tokens for new access tokens.  I'd simply _assumed_ this module did it too -- until I just looked now and found it doesn't.

I don't have time today to look into whatever library it is that's being invoked here, to map it onto my understanding of the spec underlying HTTP/REST operations.  But I believe I'll be able to it later this week sometime.

2025-07-23 21:07 UTC, jswalden requested changes

2025-07-23 21:07 UTC, jswalden commented on src/index.ts
> +					this.saveToken(JSON.stringify({ ...credentials, refresh_token: googleAuth.credentials.refresh_token }));
Sorry for delay on this.

---

Am I correct in saying that this automatic exchange of refresh for new access token only occurs _if_ the user has done a (in this case) YouTube API action?  That's basically what I interpret https://cloud.google.com/nodejs/docs/reference/google-auth-library/latest#handling-token-events to be saying.

I traced through a bunch of code in `google-auth-client`, and that was the impression I got.  Only if `getToken` in the implementation is called, will any of this fire.  (And that function is only called externally, and the internal `getTokenAsync` it calls doesn't appear to be called except by the user calling something else that would call it.)

Perhaps that's fine.  Perhaps the module _ought not_ be periodically refreshing itself if nothing is happening.  (Or perhaps it should be a config option, and users who want periodic refreshes even when they're doing nothing should opt into it, so you have natural expiration for users who are more concerned about security of just keeping usable access forever even when nothing is happening -- but this certainly would be a distinct change not to do here!)  Or perhaps this refreshing simply beats not doing it ever, so is worth doing for partial improvement even if not complete improvement.  I'd just like to be sure I understand exactly what this is doing, and to what extent it is fixing things!

---

https://cloud.google.com/nodejs/docs/reference/google-auth-library/latest#handling-token-events also seems to say Google's OAuth server returns a refresh token on first access to the token endpoint -- and then more-or-less-endlessly reuses it.  But the example they provide I think is meant to say that _if_ a refresh token is returned, it still should overwrite the previously stored one.

So -- unless I'm missing something -- I think you want to flip the ordering of member elements, like:

```
this.saveToken(JSON.stringify({
  // Continue to reuse the existing refresh token.
  refresh_token: googleAuth.credentials.refresh_token,
  // But if `credentials` contains a new refresh token,
  // it should supersede the old one.
  ...credentials,
}));
```

Does that seem right to you?  Or am I missing something here, in which case I'm happy to be informed?

2026-02-13 21:21 UTC, jswalden commented
4607f6e41899f20811528e2a914d4b7182452780 which is patterned on this PR supersedes it.  (It turns out that on closer examination neither of our approaches was entirely right.  The proposed approach here only works if the new credentials never contain a superseding refresh token -- true at least sometimes for Google but it's not obviously clear it will be always.  And my proposed response would work if the new credentials either contain a new `refresh_token` or if they _completely omit_ it, but they would not work if `credentials` contains an own property for `refresh_token` that is `undefined`.)

2026-02-13 21:21 UTC, closed without merging

2026-08-18 12:34 UTC, tbar0970 commented
@jswalden thanks for your work on this! Sorry if I've missed something: Did you submit a PR containing https://github.com/bitfocus/companion-module-youtube-live/commit/4607f6e41899f20811528e2a914d4b7182452780 or is it only in your forked repo so far?

2026-08-24 16:00 UTC, jswalden commented
Yeah, it's part of commits in at least the most recent release.